name: Enforce Labels
on: 
  pull_request:
    types: [labeled, unlabeled]

jobs:
  enforce_labels:
    runs-on: ubuntu-latest
    name: A job to enforce labels
    steps:
      - name: Enforce PR label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALID_LABELS: "bug,duplicate"
          TEST_ENV: whateverenv
        uses: ojeytonwilliams/enforce-label-action@master
        with:
          VALID_LABELS: "bug,feature"
          test_input: whateverinput
