name: Enforce Labels
on: [pull_request]

jobs:
  enforce_labels:
    runs-on: ubuntu-latest
    name: A job to enforce labels
    steps:
      - name: Enforce PR label
        uses: yogevbd/enforce-label-action@1.0.1
