name: Enforce Labels
on: [pull_request]

jobs:
  enforce_labels:
    runs-on: ubuntu-latest
    name: A job to enforce labels
    steps:
      - name: Enforce PR label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALID_LABELS: "bug,duplicate"
          TEST_ENV: whateverenv
        uses: yogevbd/enforce-label-action@1.0.1
        with:
          VALID_LABELS: "bug,feature"
          test_input: whateverinput
