name: VerifyLabels
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  label_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for failure labels
      uses: ojeytonwilliams/fail-with-these-labels-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels-to-fail: "status: blocked,status: i18n review required"
