name: VerifyLabels
on:
  pull_request:
    types: [labeled]

jobs:
  label_checker:
    runs-on: ubuntu-latest
    name: A job to check labels
    steps:
    - name: Check for failure labels
      uses: ojeytonwilliams/fail-with-these-labels-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels-to-fail: "status: blocked,status: i18n review required"
